apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummies-deployment
  labels:
    app: my-dummies-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dummies-pod
  template:
    metadata:
      labels:
        app: my-dummies-pod
    spec:
      containers:
      - name: dummies
        image: selmeczib/dummies:4
        ports:
        - containerPort: 8080
        env:
        - name: GREETING_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: greeting-config
              key: greeting
